# Generated by Django 4.2.8 on 2025-10-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quanlyhoso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCriteria',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã Tiêu Chí')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Tiêu Chí')),
                ('type', models.CharField(choices=[('QUANT', 'Định Lượng (KPI)'), ('QUAL', 'Định Tính'), ('GOAL', 'Mục Tiêu')], default='QUANT', max_length=10, verbose_name='Loại Tiêu Chí')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Trọng Số (%)')),
                ('description', models.TextField(help_text='Mô tả cách thức đánh giá và tính điểm.', verbose_name='Mô tả chi tiết')),
            ],
            options={
                'verbose_name': 'Tiêu Chí Đánh Giá',
                'verbose_name_plural': 'Danh Mục Tiêu Chí',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True, verbose_name='Ngày Đánh Giá')),
                ('period', models.CharField(help_text='Ví dụ: Q3-2024, Năm 2024', max_length=50, verbose_name='Kỳ Đánh Giá')),
                ('final_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Điểm Tổng Kết')),
            ],
            options={
                'verbose_name': 'Phiếu Đánh Giá Hiệu Suất',
                'verbose_name_plural': 'Quản Lý Đánh Giá Hiệu Suất',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tên Dự Án')),
                ('description', models.TextField(help_text='Nhập mô tả dự án', verbose_name='Mô tả')),
                ('started_date', models.DateField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('ended_date', models.DateField(null=True, verbose_name='Ngày kết thúc')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_projects', to='Quanlyhoso.nhanvien')),
                ('led_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to='Quanlyhoso.nhanvien')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Danh sách dự án',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Mã khen thưởng')),
                ('name', models.CharField(max_length=500, verbose_name='Tên hạng mục Khen thưởng')),
                ('type', models.CharField(choices=[('PERIODIC', 'Định kỳ'), ('PERFORMANCE', 'Hiệu suất')], max_length=15, verbose_name='Nhóm hạng mục')),
            ],
            options={
                'verbose_name': 'Hạng mục khen thưởng',
                'verbose_name_plural': 'Danh mục khen thưởng',
            },
        ),
        migrations.CreateModel(
            name='RewardAnnounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tên Thông báo')),
                ('budget', models.IntegerField(verbose_name='Ngân sách Khen thưởng')),
                ('maximum_employee', models.IntegerField(verbose_name='Số lượng khen thưởng tối đa')),
                ('announced_date', models.DateField(auto_now_add=True, verbose_name='Ngày thông báo khen thưởng')),
                ('description', models.TextField(help_text='Mô tả nội dung thông báo khen thưởng', verbose_name='Nội dung thông báo khen thưởng')),
                ('reward_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Khenthuong.reward', verbose_name='Hạng mục khen thưởng áp dụng')),
            ],
            options={
                'verbose_name': 'Thông báo khen thưởng',
                'verbose_name_plural': 'Lịch sử thông báo khen thưởng',
            },
        ),
        migrations.CreateModel(
            name='ScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Điểm Đạt Được')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận Xét')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Khenthuong.performancecriteria', verbose_name='Tiêu Chí')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Khenthuong.performancereview', verbose_name='Phiếu Đánh Giá')),
            ],
            options={
                'verbose_name': 'Chi Tiết Điểm Số',
                'verbose_name_plural': 'Chi Tiết Điểm Số',
                'unique_together': {('review', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='RewardSuggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Nhập lí do khen thưởng', verbose_name='Lí do khen thưởng')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=15, verbose_name='Trạng thái xét duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_suggestions', to='Quanlyhoso.nhanvien')),
                ('reward_announce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Khenthuong.rewardannounce', verbose_name='Thông báo áp dụng')),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Khenthuong.reward', verbose_name='Hạng mục nhận thưởng')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_made', to='Quanlyhoso.nhanvien')),
            ],
            options={
                'verbose_name': 'Đề xuất khen thưởng',
                'verbose_name_plural': 'Danh sách đề xuất khen thưởng',
            },
        ),
        migrations.AddField(
            model_name='performancereview',
            name='criteria',
            field=models.ManyToManyField(through='Khenthuong.ScoreDetail', to='Khenthuong.performancecriteria', verbose_name='Các Tiêu Chí Áp Dụng'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='Quanlyhoso.nhanvien'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='Quanlyhoso.nhanvien'),
        ),
        migrations.CreateModel(
            name='RewardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewarded_value', models.IntegerField(verbose_name='Giá trị Khen thưởng')),
                ('rewarded_date', models.DateField(auto_now_add=True, verbose_name='Ngày khen thưởng')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_lists', to='Quanlyhoso.nhanvien')),
                ('reward_announce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Khenthuong.rewardannounce', verbose_name='Thông báo áp dụng')),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Khenthuong.reward', verbose_name='Hạng mục nhận thưởng')),
            ],
            options={
                'verbose_name': 'Khen thưởng',
                'verbose_name_plural': 'Danh sách khen thưởng',
                'unique_together': {('employee', 'reward_announce')},
            },
        ),
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Thành viên', max_length=100, verbose_name='Vai trò')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='Ngày tham gia')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='Quanlyhoso.nhanvien')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Khenthuong.project', verbose_name='Mã Dự Án')),
            ],
            options={
                'ordering': ['-project', 'employee'],
                'unique_together': {('project', 'employee', 'role')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('employee', 'period')},
        ),
    ]
