# Generated by Django 4.2.8 on 2025-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlyhoso', '0001_initial'),
        ('Khenthuong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(related_name='employee_projects', through='Khenthuong.ProjectEmployee', to='Quanlyhoso.nhanvien'),
        ),
    ]
