# Generated by Django 4.2.8 on 2025-11-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên phòng ban')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phòng Ban',
                'verbose_name_plural': 'Các Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=50, verbose_name='Họ và tên nhân viên')),
                ('started_date', models.DateField(verbose_name='Ngày bắt đầu làm việc')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Ảnh đại diện')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('cic', models.CharField(blank=True, max_length=20, verbose_name='Số CMND/CCCD')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quanlyhoso.department', verbose_name='Phòng ban')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quanlyhoso.employee', verbose_name='Người quản lý trực tiếp')),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Các Nhân Viên',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên chức vụ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Chức Vụ',
                'verbose_name_plural': 'Các Chức Vụ',
            },
        ),
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Họ và tên mới')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar_requests/', verbose_name='Ảnh đại diện mới')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh mới')),
                ('gender', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, null=True, verbose_name='Giới tính mới')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại mới')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ mới')),
                ('cic', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CMND/CCCD mới')),
                ('status', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Bị từ chối', 'Bị từ chối')], default='Chờ duyệt', max_length=50, verbose_name='Trạng thái')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày yêu cầu')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý')),
                ('hr_note', models.TextField(blank=True, verbose_name='Ghi chú của HR (nếu từ chối)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='Quanlyhoso.employee', verbose_name='Nhân viên')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_profile_updates', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Yêu cầu Cập nhật Hồ sơ',
                'verbose_name_plural': 'Các Yêu cầu Cập nhật Hồ sơ',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('Phép năm', 'Phép năm'), ('Nghỉ ốm', 'Nghỉ ốm'), ('Nghỉ không lương', 'Nghỉ không lương'), ('Khác', 'Khác')], max_length=50, verbose_name='Loại nghỉ phép')),
                ('started_date', models.DateField(verbose_name='Ngày bắt đầu nghỉ')),
                ('ended_date', models.DateField(verbose_name='Ngày kết thúc nghỉ')),
                ('total_days_off', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Tổng số ngày nghỉ')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('status', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Bị từ chối', 'Bị từ chối')], default='Chờ duyệt', max_length=50, verbose_name='Trạng thái')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi đơn')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú của quản lý')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_nghi_phep', to='Quanlyhoso.employee', verbose_name='Nhân viên')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý (Quản lý)')),
            ],
            options={
                'verbose_name': 'Đơn Nghỉ Phép',
                'verbose_name_plural': 'Các Đơn Nghỉ Phép',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quanlyhoso.position', verbose_name='Chức vụ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản đăng nhập'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Số hợp đồng')),
                ('contract_type', models.CharField(choices=[('Thử việc', 'Thử việc'), ('Xác định thời hạn 1 năm', 'Xác định thời hạn 1 năm'), ('Xác định thời hạn 3 năm', 'Xác định thời hạn 3 năm'), ('Không xác định thời hạn', 'Không xác định thời hạn'), ('Thời vụ', 'Thời vụ')], max_length=100, verbose_name='Loại hợp đồng')),
                ('signed_date', models.DateField(verbose_name='Ngày ký')),
                ('started_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('ended_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn (nếu có)')),
                ('basic_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('file_scan', models.FileField(blank=True, null=True, upload_to='hop_dong/', verbose_name='File scan hợp đồng')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong', to='Quanlyhoso.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Hợp Đồng',
                'verbose_name_plural': 'Các Hợp Đồng',
                'ordering': ['-started_date'],
            },
        ),
    ]
