# Generated by Django 4.2.8 on 2025-10-27 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuc_vu', models.CharField(max_length=200, unique=True, verbose_name='Tên chức vụ')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Chức Vụ',
                'verbose_name_plural': 'Các Chức Vụ',
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_ban', models.CharField(max_length=200, unique=True, verbose_name='Tên phòng ban')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phòng Ban',
                'verbose_name_plural': 'Các Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và Tên')),
                ('ma_nhan_vien', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('ngay_bat_dau_lam', models.DateField(verbose_name='Ngày bắt đầu làm việc')),
                ('trang_thai', models.CharField(choices=[('Đang làm việc', 'Đang làm việc'), ('Đã nghỉ việc', 'Đã nghỉ việc'), ('Thử việc', 'Thử việc')], default='Thử việc', max_length=50, verbose_name='Trạng thái')),
                ('so_ngay_phep_nam_con_lai', models.DecimalField(decimal_places=1, default=12.0, max_digits=4, verbose_name='Số ngày phép năm còn lại')),
                ('email', models.EmailField(default='temp@example.com', max_length=255, verbose_name='Địa chỉ Email')),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='anh_dai_dien/', verbose_name='Ảnh đại diện')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('dia_chi', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('so_cmnd_cccd', models.CharField(blank=True, max_length=20, verbose_name='Số CMND/CCCD')),
                ('ngay_cap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('noi_cap', models.CharField(blank=True, max_length=200, verbose_name='Nơi cấp')),
                ('ma_so_thue', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('so_so_bhxh', models.CharField(blank=True, max_length=20, verbose_name='Số sổ BHXH')),
                ('chuc_vu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quanlyhoso.chucvu', verbose_name='Chức vụ')),
                ('nguoi_quan_ly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quanlyhoso.nhanvien', verbose_name='Người quản lý trực tiếp')),
                ('phong_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quanlyhoso.phongban', verbose_name='Phòng ban')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Các Nhân Viên',
            },
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hop_dong', models.CharField(max_length=100, unique=True, verbose_name='Số hợp đồng')),
                ('loai_hop_dong', models.CharField(choices=[('Thử việc', 'Thử việc'), ('Xác định thời hạn 1 năm', 'Xác định thời hạn 1 năm'), ('Xác định thời hạn 3 năm', 'Xác định thời hạn 3 năm'), ('Không xác định thời hạn', 'Không xác định thời hạn'), ('Thời vụ', 'Thời vụ')], max_length=100, verbose_name='Loại hợp đồng')),
                ('ngay_ky', models.DateField(verbose_name='Ngày ký')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày hiệu lực')),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn (nếu có)')),
                ('luong_co_ban', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('file_scan', models.FileField(blank=True, null=True, upload_to='hop_dong/', verbose_name='File scan hợp đồng')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong', to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Hợp Đồng',
                'verbose_name_plural': 'Các Hợp Đồng',
                'ordering': ['-ngay_bat_dau'],
            },
        ),
        migrations.CreateModel(
            name='DonNghiPhep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_nghi_phep', models.CharField(choices=[('Phép năm', 'Phép năm'), ('Nghỉ ốm', 'Nghỉ ốm'), ('Nghỉ không lương', 'Nghỉ không lương'), ('Khác', 'Khác')], max_length=50, verbose_name='Loại nghỉ phép')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu nghỉ')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Ngày kết thúc nghỉ')),
                ('so_ngay_nghi', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Tổng số ngày nghỉ')),
                ('ly_do', models.TextField(verbose_name='Lý do')),
                ('trang_thai', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Bị từ chối', 'Bị từ chối')], default='Chờ duyệt', max_length=50, verbose_name='Trạng thái')),
                ('ngay_gui_don', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi đơn')),
                ('ghi_chu_quan_ly', models.TextField(blank=True, verbose_name='Ghi chú của quản lý')),
                ('nguoi_xu_ly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_duyet_don', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý (Quản lý)')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_nghi_phep', to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Đơn Nghỉ Phép',
                'verbose_name_plural': 'Các Đơn Nghỉ Phép',
                'ordering': ['-ngay_gui_don'],
            },
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cham_cong', models.DateField(verbose_name='Ngày chấm công')),
                ('gio_vao', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('gio_ra', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('trang_thai', models.CharField(choices=[('Đúng giờ', 'Đúng giờ'), ('Đi trễ', 'Đi trễ'), ('Về sớm', 'Về sớm'), ('Vắng mặt', 'Vắng mặt'), ('Nghỉ phép', 'Nghỉ phép')], default='Đúng giờ', max_length=50, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cham_cong', to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm Công',
                'verbose_name_plural': 'Dữ Liệu Chấm Công',
                'ordering': ['-ngay_cham_cong', 'nhan_vien'],
                'unique_together': {('nhan_vien', 'ngay_cham_cong')},
            },
        ),
    ]
