# Generated by Django 4.2.8 on 2025-11-12 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quanlyhoso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Tên khóa học hoặc chủ đề')),
                ('reason', models.TextField(verbose_name='Lý do/Mục tiêu đào tạo')),
                ('status', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Bị từ chối', 'Bị từ chối')], default='Chờ duyệt', max_length=50, verbose_name='Trạng thái')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi yêu cầu')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý')),
                ('hr_note', models.TextField(blank=True, verbose_name='Ghi chú của HR (nếu từ chối)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='Quanlyhoso.employee', verbose_name='Nhân viên')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_training_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Yêu cầu Đào tạo',
                'verbose_name_plural': 'Các Yêu cầu Đào tạo',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
