# Generated by Django 4.2.8 on 2025-10-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlyhoso', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChamCong',
        ),
    ]
