# Generated by Django 4.2.8 on 2025-10-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlyhoso', '0002_delete_chamcong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='fullname',
        ),
    ]
