# Generated by Django 4.2.8 on 2025-11-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Tiêu đề bài đăng')),
                ('content', models.TextField(verbose_name='Thông tin bài đăng')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('status', models.CharField(choices=[('CLOSED', 'Đã tuyển đủ'), ('OPEN', 'Đang tuyển')], default='OPEN', max_length=10, verbose_name='Trạng thái tuyển dụng')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kỹ năng')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Họ và Tên')),
                ('email', models.EmailField(max_length=255, verbose_name='Địa chỉ Email')),
                ('study', models.CharField(max_length=255, verbose_name='Trình độ học vấn')),
                ('linkCV', models.URLField(verbose_name='Liên kết CV')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('gender', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, null=True)),
                ('review_status', models.CharField(blank=True, choices=[('APPLIED', 'Ứng tuyển'), ('SCREENING', 'Sàng lọc'), ('PASSED', 'Đạt'), ('FAILED', 'Không đạt')], default='APPLIED', max_length=20, null=True, verbose_name='Trạng thái xét duyệt')),
                ('interview_result', models.CharField(blank=True, choices=[('PASSED', 'Đạt'), ('FAILED', 'Không đạt')], max_length=10, null=True, verbose_name='Trạng thái sau phỏng vấn')),
                ('offer_status', models.CharField(blank=True, choices=[('ACCEPTED', 'Ứng viên đồng ý'), ('REJECTED', 'Ứng viên từ chối'), ('EXPIRED', 'Quá hạn không phản hồi')], max_length=30, null=True, verbose_name='Trạng thái gửi offer')),
                ('training_status', models.CharField(blank=True, choices=[('PASSED', 'Đạt')], max_length=10, null=True, verbose_name='Trạng thái sau phỏng vấn')),
                ('official_status', models.CharField(blank=True, choices=[('PASSED', 'Đạt')], max_length=10, null=True, verbose_name='Trạng thái sau phỏng vấn')),
                ('skill', models.ManyToManyField(to='Quanlytuyendung.skill', verbose_name='Kỹ năng')),
            ],
        ),
    ]
