# Generated by Django 4.2.8 on 2025-10-19 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Họ và Tên')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('phonenumber', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=255, verbose_name='Địa chỉ Email')),
                ('study', models.CharField(max_length=255, verbose_name='Trình độ học vấn')),
                ('linkCV', models.URLField(verbose_name='Liên kết CV')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Thông tin bài đăng')),
                ('date_posted', models.DateField(verbose_name='Ngày đăng')),
                ('status', models.CharField(choices=[('CLOSED', 'Đã tuyển đủ'), ('OPEN', 'Đang tuyển')], default='OPEN', max_length=10, verbose_name='Trạng thái tuyển dụng')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kỹ năng')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(blank=True, choices=[('APPLIED', 'Ứng tuyển'), ('SCREENING', 'Sàng lọc'), ('PASSED', 'Đạt'), ('FAILED', 'Không đạt')], default='APPLIED', max_length=20, null=True, verbose_name='Trạng thái xét duyệt')),
                ('interview_result', models.CharField(blank=True, choices=[('PASSED', 'Đạt'), ('FAILED', 'Không đạt')], max_length=10, null=True, verbose_name='Trạng thái sau phỏng vấn')),
                ('offer_status', models.CharField(blank=True, choices=[('ACCEPTED', 'Ứng viên đồng ý'), ('REJECTED', 'Ứng viên từ chối'), ('EXPIRED', 'Quá hạn không phản hồi')], max_length=30, null=True, verbose_name='Trạng thái gửi offer')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlytuyendung.candidatefile', verbose_name='Mã số ứng viên')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_status', models.CharField(default='Đạt', editable=False, max_length=10, verbose_name='Trạng thái đào tạo')),
                ('official_status', models.CharField(default='Thành công', editable=False, max_length=20, verbose_name='Trạng thái chính thức hóa')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Quanlytuyendung.candidatefile', verbose_name='Mã số ứng viên')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Quanlytuyendung.status', verbose_name='Mã trạng thái offer thành công')),
            ],
        ),
        migrations.AddField(
            model_name='candidatefile',
            name='skill',
            field=models.ManyToManyField(to='Quanlytuyendung.skill', verbose_name='Kỹ năng'),
        ),
    ]
