# Generated by Django 4.2.8 on 2025-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlytuyendung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruitment_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=255, verbose_name='Họ và tên Quản lý')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('department', models.CharField(max_length=200, verbose_name='Tên phòng ban')),
                ('request_name', models.TextField(verbose_name='Tên yêu cầu tuyển dụng')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng người cần tuyển dụng')),
                ('request_status', models.CharField(blank=True, choices=[('CONSIDERING', 'Đang xem xét'), ('ACCEPTED', 'Chấp nhận'), ('REJECTED', 'Từ chối')], default='CONSIDERING', max_length=20, null=True, verbose_name='Trạng thái xét duyệt')),
                ('reason', models.TextField(verbose_name='Lý do tuyển dụng')),
                ('job_description', models.TextField(verbose_name='Mô tả công việc')),
                ('request_skill_needed', models.TextField(null=True, verbose_name='Kỹ năng')),
                ('date_requested', models.DateField(auto_now_add=True, verbose_name='Ngày gửi yêu cầu')),
                ('date_job_start', models.DateField(null=True, verbose_name='Ngày yêu cầu nhận việc')),
                ('recruitment_position', models.CharField(max_length=100, verbose_name='Vị trí tuyển dụng')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mức lương tối thiểu (VNĐ)')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mức lương tối đa (VNĐ)')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidatefile',
            name='linkCV',
        ),
        migrations.AddField(
            model_name='candidatefile',
            name='apply_position',
            field=models.CharField(max_length=100, null=True, verbose_name='Vị trí ứng tuyển'),
        ),
        migrations.AddField(
            model_name='candidatefile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
        migrations.AddField(
            model_name='recruitmentpost',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Toàn thời gian'), ('Intern', 'Thực tập'), ('Contract', 'Hợp đồng')], default='Full-time', max_length=20, null=True, verbose_name='Hình thức làm việc'),
        ),
        migrations.AddField(
            model_name='recruitmentpost',
            name='post_skill_needed',
            field=models.TextField(null=True, verbose_name='Kỹ năng'),
        ),
        migrations.AddField(
            model_name='recruitmentpost',
            name='salary',
            field=models.CharField(blank=True, help_text='Ví dụ: 20-30 triệu / Theo năng lực', max_length=100, null=True, verbose_name='Mức lương'),
        ),
    ]
