# Generated by Django 4.2.8 on 2025-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlytuyendung', '0002_recruitment_request_remove_candidatefile_linkcv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatefile',
            name='official_status',
            field=models.CharField(blank=True, choices=[('PASSED', 'Đạt')], max_length=10, null=True, verbose_name='Trạng thái chính thức '),
        ),
        migrations.AlterField(
            model_name='candidatefile',
            name='training_status',
            field=models.CharField(blank=True, choices=[('PASSED', 'Đạt')], max_length=10, null=True, verbose_name='Trạng thái đào tạo'),
        ),
    ]
