# Generated by Django 4.2.8 on 2025-11-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quanlyhoso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kỳ lương')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('standard_working_days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Số ngày công chuẩn')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Đã chốt kỳ')),
            ],
            options={
                'verbose_name': 'Kỳ Lương',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên thành phần')),
                ('component_type', models.CharField(choices=[('BASE', 'Lương Cơ Bản'), ('ALLOWANCE', 'Phụ Cấp'), ('BONUS', 'Thưởng')], default='BASE', max_length=10, verbose_name='Loại thành phần')),
            ],
            options={
                'verbose_name': 'Thành phần Lương',
            },
        ),
        migrations.CreateModel(
            name='VariableBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền thưởng')),
                ('component', models.ForeignKey(limit_choices_to={'component_type': 'BONUS'}, on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.salarycomponent', verbose_name='Loại thưởng')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.payrollperiod', verbose_name='Kỳ lương')),
            ],
            options={
                'verbose_name': 'Thưởng Biến đổi',
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luong_co_ban', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Lương cơ bản (Rate)')),
                ('so_ngay_cong_thuc_te', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ngày công thực tế')),
                ('so_ngay_cong_chuan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ngày công chuẩn')),
                ('tong_phu_cap', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tổng Phụ cấp')),
                ('tong_thuong', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tổng Thưởng')),
                ('thuc_linh', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Thực lĩnh')),
                ('calculated_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tính')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.payrollperiod', verbose_name='Kỳ lương')),
            ],
            options={
                'verbose_name': 'Bảng Lương Đã Tính',
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('component', models.ForeignKey(limit_choices_to={'component_type__in': ['BASE', 'ALLOWANCE']}, on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.salarycomponent', verbose_name='Thành phần lương')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_details', to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Lương Cố định Nhân viên',
                'unique_together': {('employee', 'component')},
            },
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cham_cong', models.DateField(verbose_name='Ngày chấm công')),
                ('gio_vao', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('gio_ra', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('trang_thai', models.CharField(choices=[('Đúng giờ', 'Đúng giờ'), ('Đi trễ', 'Đi trễ'), ('Về sớm', 'Về sớm'), ('Vắng mặt', 'Vắng mặt'), ('Nghỉ phép', 'Nghỉ phép')], default='Đúng giờ', max_length=50, verbose_name='Trạng thái')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cham_cong', to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm Công',
                'verbose_name_plural': 'Dữ Liệu Chấm Công',
                'ordering': ['-ngay_cham_cong', 'nhan_vien'],
                'unique_together': {('nhan_vien', 'ngay_cham_cong')},
            },
        ),
    ]
