# Generated by Django 4.2.8 on 2025-10-24 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='Mã định danh duy nhất của nhân viên.', max_length=10, unique=True)),
                ('first_names', models.CharField(help_text='Tên của nhân viên.', max_length=50)),
                ('last_names', models.CharField(help_text='Họ của nhân viên.', max_length=50)),
                ('salary_level', models.IntegerField(blank=True, help_text='Bậc lương để xác định mức lương cơ bản.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên thành phần lương (ví dụ: Lương Cơ Bản, Phụ Cấp Ăn Trưa).', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền cố định của thành phần này.', max_digits=10)),
                ('is_deduction', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là khoản khấu trừ (ví dụ: Bảo hiểm xã hội).')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField(help_text='Ngày bắt đầu kỳ tính lương.')),
                ('period_end_date', models.DateField(help_text='Ngày kết thúc kỳ tính lương.')),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Tổng lương trước thuế.', max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, help_text='Tổng các khoản khấu trừ (thuế, bảo hiểm...).', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Lương thực nhận (Net Salary).', max_digits=12)),
                ('is_paid', models.BooleanField(default=False, help_text='Trạng thái đã thanh toán.')),
                ('employee', models.ForeignKey(help_text='Nhân viên nhận bảng lương.', on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.employee')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Người dùng (admin) đã xử lý bảng lương.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('BONUS', 'Thưởng'), ('DEDUCTION', 'Khấu Trừ/Phạt'), ('ALLOWANCE', 'Phụ Cấp Khác')], help_text='Loại điều chỉnh (Thưởng, Phạt, Phụ cấp).', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền điều chỉnh.', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú chi tiết về khoản điều chỉnh.')),
                ('employee', models.ForeignKey(help_text='Nhân viên áp dụng khoản điều chỉnh.', on_delete=django.db.models.deletion.CASCADE, to='Tinhluong.employee')),
                ('payroll_record', models.ForeignKey(blank=True, help_text='Bảng lương mà điều chỉnh này được áp dụng.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tinhluong.payrollrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='Ngày đầu tiên của tháng tính lương.', verbose_name='Tháng tính lương')),
                ('working_days', models.FloatField(help_text='Số ngày công thực tế.')),
                ('overtime_hours', models.IntegerField(default=0, help_text='Số giờ tăng ca (nếu có).')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ Duyệt'), ('APPROVED', 'Đã Duyệt'), ('REJECTED', 'Từ Chối')], default='PENDING', help_text='Trạng thái của bảng chấm công.', max_length=10)),
                ('employee', models.ForeignKey(help_text='Nhân viên có bảng chấm công này.', on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.employee')),
            ],
            options={
                'unique_together': {('employee', 'month_year')},
            },
        ),
    ]
