# Generated by Django 4.2.8 on 2025-10-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlyhoso', '0002_delete_chamcong'),
        ('Tinhluong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cham_cong', models.DateField(verbose_name='Ngày chấm công')),
                ('gio_vao', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('gio_ra', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('trang_thai', models.CharField(choices=[('Đúng giờ', 'Đúng giờ'), ('Đi trễ', 'Đi trễ'), ('Về sớm', 'Về sớm'), ('Vắng mặt', 'Vắng mặt'), ('Nghỉ phép', 'Nghỉ phép')], default='Đúng giờ', max_length=50, verbose_name='Trạng thái')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cham_cong', to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm Công',
                'verbose_name_plural': 'Dữ Liệu Chấm Công',
                'ordering': ['-ngay_cham_cong', 'nhan_vien'],
                'unique_together': {('nhan_vien', 'ngay_cham_cong')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
            ],
            options={
                'verbose_name': 'Lương Cố định Nhân viên',
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luong_co_ban', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Lương cơ bản (Rate)')),
                ('so_ngay_cong_thuc_te', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ngày công thực tế')),
                ('so_ngay_cong_chuan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ngày công chuẩn')),
                ('tong_phu_cap', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tổng Phụ cấp')),
                ('tong_thuong', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tổng Thưởng')),
                ('thuc_linh', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Thực lĩnh')),
                ('calculated_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tính')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Quanlyhoso.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bảng Lương Đã Tính',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kỳ lương')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('standard_working_days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Số ngày công chuẩn')),
            ],
            options={
                'verbose_name': 'Kỳ Lương',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VariableBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền thưởng')),
            ],
            options={
                'verbose_name': 'Thưởng Biến đổi',
            },
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='processed_by',
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='salarycomponent',
            options={'verbose_name': 'Thành phần Lương'},
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='is_deduction',
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='component_type',
            field=models.CharField(choices=[('BASE', 'Lương Cơ Bản'), ('ALLOWANCE', 'Phụ Cấp'), ('BONUS', 'Thưởng')], default='BASE', max_length=10, verbose_name='Loại thành phần'),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên thành phần'),
        ),
        migrations.DeleteModel(
            name='CustomAdjustment',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
        migrations.DeleteModel(
            name='Timesheet',
        ),
        migrations.AddField(
            model_name='variablebonus',
            name='component',
            field=models.ForeignKey(limit_choices_to={'component_type': 'BONUS'}, on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.salarycomponent', verbose_name='Loại thưởng'),
        ),
        migrations.AddField(
            model_name='variablebonus',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Quanlyhoso.nhanvien', verbose_name='Nhân viên'),
        ),
        migrations.AddField(
            model_name='variablebonus',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.payrollperiod', verbose_name='Kỳ lương'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.payrollperiod', verbose_name='Kỳ lương'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='component',
            field=models.ForeignKey(limit_choices_to={'component_type__in': ['BASE', 'ALLOWANCE']}, on_delete=django.db.models.deletion.PROTECT, to='Tinhluong.salarycomponent', verbose_name='Thành phần lương'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_details', to='Quanlyhoso.nhanvien', verbose_name='Nhân viên'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollentry',
            unique_together={('employee', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('employee', 'component')},
        ),
    ]
