# Generated by Django 4.2.8 on 2025-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tinhluong', '0002_chamcong_employeesalary_payrollentry_payrollperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang áp dụng'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Đã chốt kỳ'),
        ),
    ]
